import { Metadata } from "next";
import Button from "../../components/ui/button";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="flex flex-col gap-4">
      <h1>AboutPage</h1>
      <a href="/">
        <Button>Home anchor</Button>
      </a>

      <Link href="/">
        <Button>Home next link</Button>
      </Link>
    </div>
  );
};

export default AboutPage;
